{% set name = "cellpy" %}
{% set version = "0.3.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e4013ecdf589e7c731e41f123ce3fe7748d43a468d5e86af35466c18ef74aea5

build:
  number: 0
  entry_points:
    - cellpy=cellpy.cli:cli

requirements:
  host:
    - pip
    - python
    - setuptools >=38.6.0
  run:
    - python >=3.6
    - pytables >=3.5.1
    - pyodbc >=4.0.16  # [win]
    - click
    - matplotlib
    - numpy >=1.16.4
    - pandas
    - python-box
    - pyyaml >=4.2b1
    - scipy
    - setuptools
    - xlrd
    - lmfit
    - PyGithub >=1.43.0

test:
  requires:
    - pytest
    - matplotlib
    - pytest-benchmark
    - pytest-timeout
  imports:
    - cellpy
    - cellpy.parameters
    - cellpy.readers
    - cellpy.readers.instruments
    - cellpy.utils
    - tests
  commands:
    - cellpy --help

about:
  home: https://github.com/jepegit/cellpy
  license: MIT
  license_family: MIT
  license_file:
  summary: Extract data from battery cell testers.
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - jepegit

