name: cellpy_dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - xlrd
  - matplotlib
  - cryptography
  - click
  - scipy
  - pandas
  - pytables
  - setuptools
  - pyyaml
  - pyodbc
  - pip:
    - lmfit
    - python-box

