name: cellpy_dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - numpy=1.15.4
  - xlrd
  - matplotlib
  - cryptography
  - click
  - scipy
  - pandas
  - pytables
  - setuptools
  - pyyaml
  - pyodbc
  - coverage
  - wheel
  - flake8
  - Sphinx
  - PyGithub
  - watchdog
  - pytest
  - twine
  - pip:
    - lmfit
    - python-box
    - pytest-benchmark
    - pytest-timeout

