name: cellpy_dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.7
  - pip
  - numpy
  - xlrd
  - matplotlib
  - cryptography
  - click
  - scipy
  - pandas
  - pytables>=3.5.1
  - setuptools
  - pyyaml>=4.2b1
  - pyodbc
  - coverage
  - wheel
  - flake8
  - Sphinx
  - PyGithub
  - watchdog
  - pytest
  - twine
  - invoke
  - conda-build
  - ripgrep
  - conda-verify
  - anaconda-client
  - lmfit
  - cookiecutter
  - pip:
    - python-box<4
    - pytest-benchmark
    - pytest-timeout
    - requests

