name: cellpy
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6
  - pip
  - numpy
  - xlrd
  - matplotlib
  - cryptography
  - click
  - scipy
  - pandas
  - pytables>=3.5.1
  - setuptools
  - pyyaml>=4.2b1
  - pyodbc
  - PyGithub
  - cookiecutter
  - tqdm
  - pip:
    - lmfit
    - python-box<4

