name: cellpy
channels:
  - defaults
  - conda-forge
  - pyviz
dependencies:
  - python>=3.6
  - pip
  - numpy
  - xlrd
  - matplotlib
  - cryptography
  - click
  - scipy
  - pandas
  - pytables>=3.6.1
  - setuptools
  - ruamel.yaml
  - pyodbc
  - PyGithub
  - cookiecutter
  - tqdm
  - ipywidgets
  - lmfit
  - ipykernel
  - holoviz
  - hdf5
  - pytables
  - python-box

