name: cellpy
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6
  - pip
  - numpy
  - xlrd
  - matplotlib
  - cryptography
  - click
  - scipy
  - pandas
  - pytables>=3.5.1
  - setuptools
  - ruamel.yaml
  - pyodbc
  - PyGithub
  - pip:
    - lmfit
    - python-box

