package:
  name: cellpy
  version: "0.2.0"

source:
  git_rev: release/v.0.2.0
  git_url: https://github.com/jepegit/cellpy

requirements:
  host:
    - python >= 3.6
    - setuptools

  run:
    - python >= 3.6
    - python>=3.6
    - numpy
    - xlrd
    - matplotlib
    - cryptography
    - click
    - scipy
    - pandas
    - pytables
    - setuptools
    - pyyaml
    - pip:
      - lmfit
      - python-box

test:
  requires:
    - pytest
  imports:
    -

about:
  home:
  license:
  license_file:
